const crypto=require("crypto"),fs=require("fs"),path=require("path");
const {acquireWriterLease,releaseWriterLease}=require("../orchestration/writer-lease");
const {loadJson,readJsonl,backupFile,replaceTextAtomic,writeJsonAtomic}=require("./continuity-store");
const {DEFAULT_AUTOMATION_TIMEZONE,localDateKey}=require("../utils/business-day");
class WeeklyReflect {
 constructor({continuityDir,now=()=>new Date(),random=Math.random,automationTimezone=DEFAULT_AUTOMATION_TIMEZONE}={}){this.dir=continuityDir;this.now=now;this.random=random;this.automationTimezone=automationTimezone;this.p={episodes:path.join(continuityDir,"episodes.jsonl"),notes:path.join(continuityDir,"ai_self_notes.md"),rereadings:path.join(continuityDir,"rereadings.md"),state:path.join(continuityDir,".jobs","weekly-reflect.json"),lease:path.join(continuityDir,".jobs","weekly-reflect-lease.json"),backups:path.join(continuityDir,".backups")};}
 async run({runtime}={}){const now=this.now(),week=weekKey(now,this.automationTimezone),state=loadJson(this.p.state,{weeks:{}});if(state.weeks?.[week])return {status:"skipped",reason:"already_ran",week};let lease;try{lease=acquireWriterLease(this.p.lease,{writer:"weekly-reflect",model:"subject-runtime",phase:"fable",branch:"feat/fable-wishlist-20260713",worktree:this.dir,base_sha:"0".repeat(40)},{recoverStale:true});}catch{return {status:"skipped",reason:"lease_unavailable",week};}try{const current=loadJson(this.p.state,{weeks:{}});if(current.weeks?.[week])return {status:"skipped",reason:"already_ran",week};const all=readJsonl(this.p.episodes),choices=all.length>1?all.slice(0,-1):all;if(!choices.length)return complete(this.p,current,week,{status:"no_change",reason:"no_episodes"});const episode=choices[Math.min(choices.length-1,Math.floor(this.random()*choices.length))],id=String(episode.ep_id||episode.id||"");if(!id)return complete(this.p,current,week,{status:"no_change",reason:"invalid_episode"});const notes=recentNotes(this.p.notes);const key=hash(`${week}\n${id}`),marker=`<!-- weekly-reflect:${key} -->`,existing=read(this.p.rereadings);if(existing.includes(marker))return complete(this.p,current,week,{status:"success",episode_id:id,idempotency_key:key,recovered:true});const raw=typeof runtime?.reflect==="function"?await runtime.reflect({episode,notes,date:dateKey(now,this.automationTimezone)}):"";const text=typeof raw==="string"?raw.trim():String(raw?.text||"").trim();if(!text)return complete(this.p,current,week,{status:"no_change",reason:"runtime_empty",episode_id:id,idempotency_key:key});backupFile(this.p.rereadings,this.p.backups);replaceTextAtomic(this.p.rereadings,`${existing}${existing&&!existing.endsWith("\n")?"\n":""}${marker}\n${dateKey(now,this.automationTimezone)} · ${id} · ${text}\n`);return complete(this.p,current,week,{status:"success",episode_id:id,idempotency_key:key});}finally{releaseWriterLease(this.p.lease,lease.lease_id);}}
}
function complete(p,state,week,result){state.weeks=state.weeks||{};state.weeks[week]={completed_at:new Date().toISOString(),...result};writeJsonAtomic(p.state,state);return {...result,week};}function read(f){try{return fs.readFileSync(f,"utf8")}catch{return ""}}function recentNotes(f){return read(f).split(/\r?\n/u).filter(x=>x.trim()).slice(-5).join("\n").slice(-1200);}function hash(x){return crypto.createHash("sha256").update(x).digest("hex");}function dateKey(d,automationTimezone=DEFAULT_AUTOMATION_TIMEZONE){return localDateKey(d,automationTimezone)||new Date(d).toISOString().slice(0,10);}function weekKey(d,automationTimezone=DEFAULT_AUTOMATION_TIMEZONE){const [y,m,day]=dateKey(d,automationTimezone).split("-").map(Number),x=new Date(Date.UTC(y,m-1,day)),w=(x.getUTCDay()+6)%7;x.setUTCDate(x.getUTCDate()-w);return x.toISOString().slice(0,10);}module.exports={WeeklyReflect,weekKey};
